// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANcaMjPNb41Ge9RnR6R5kEeEZu7OmTIio',
    appId: '1:242030683456:web:5173d237ea89a79e1106a5',
    messagingSenderId: '242030683456',
    projectId: 'gym-database01',
    authDomain: 'gym-database01.firebaseapp.com',
    storageBucket: 'gym-database01.firebasestorage.app',
    measurementId: 'G-VHWVMSETZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxJeSieGFcYOYWJernCcH-lSMfLm6PWiQ',
    appId: '1:242030683456:android:ced56d610c01553d1106a5',
    messagingSenderId: '242030683456',
    projectId: 'gym-database01',
    storageBucket: 'gym-database01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmm5ruCfbfmrv5mpHZT2jvbKnSADaI3ko',
    appId: '1:242030683456:ios:f41d13ac8df42c4b1106a5',
    messagingSenderId: '242030683456',
    projectId: 'gym-database01',
    storageBucket: 'gym-database01.firebasestorage.app',
    iosBundleId: 'com.example.gymSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmm5ruCfbfmrv5mpHZT2jvbKnSADaI3ko',
    appId: '1:242030683456:ios:f41d13ac8df42c4b1106a5',
    messagingSenderId: '242030683456',
    projectId: 'gym-database01',
    storageBucket: 'gym-database01.firebasestorage.app',
    iosBundleId: 'com.example.gymSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANcaMjPNb41Ge9RnR6R5kEeEZu7OmTIio',
    appId: '1:242030683456:web:dfc73f09ed5f96841106a5',
    messagingSenderId: '242030683456',
    projectId: 'gym-database01',
    authDomain: 'gym-database01.firebaseapp.com',
    storageBucket: 'gym-database01.firebasestorage.app',
    measurementId: 'G-NXJNSPMF3P',
  );
}
